### ISSUE TITLE
Bloxshade a lil sketch

### ISSUE THREAD

**Issue by ToxicTDX** [Extravi/Bloxshade#40]
https://hybrid-analysis.com/sample/d4b958647ab9da0077d0954e176026e31d8a333b0b2a2f3665315aab4dec2c0e/66c9bcd8423b0a075f0a04f9

I ran it on a vm and you decide to have anti-vm here? My bad, why is there any dang reason for you to have anti-vm for a roblox shader??? Hybrid analysis says its 100/100 malicious, but everything else is seemingly fine. Why do you need anti-vm?

**Comment by Extravi** [comment]
do you realize that this is the source code for the installer? you could check the code yourself instead of asking this question?

here's the line of code that makes it think it has anti-vm: https://github.com/Extravi/Bloxshade/blob/main/bloxshade%2Fstart%2Fsrc%2Fmain.cpp#L93

it does that regardless of whether or not it's in a VM so it doesn't have any unnecessary processes running and it only has one process of itself.
