### ISSUE TITLE
[BUG] Bloxshade not working / installing with new Bloxstrap update

### ISSUE THREAD

**Issue by daflame899** [Extravi/Bloxshade#53]
[bloxshade_no](https://github.com/user-attachments/assets/17e5f57c-6ed4-479b-b97a-1f3584bbd184)

**Comment by abeba-boop** [comment]
any answear still?

**Comment by Elite-Nuke** [comment]
same here it just says fail to open file even tho i'm running as admin

**Comment by Extravi** [comment]
bloxstrap updated how it handles its file path in version 2.8.0 and i have not had time to update bloxshade yet

**Comment by Extravi** [comment]
im busy with mid term test and school atm

**Comment by Elite-Nuke** [comment]
oh type shit i'm doing one rn, if you dont mind sending a message here once you update it i'd appreciate that

**Comment by abeba-boop** [comment]
ok i think i found a workaround you guys need roblox for this to get shortcuts,so you need to install shortcuts or eurotrucks2.exe to be in folder of roblox then you put eurotrucks2.exe in folder of bloxstrap then you gotta launch roblox useing eurotrucks2 NOT thoruth bloxstrap or website.You could also do a shortcut if you don't want to open folder everytime.
Some features will not work that's sad ![helper](https://github.com/user-attachments/assets/abbb3b42-26fa-4392-9341-29cae96fc038)

**Comment by OR555** [comment]
You don't need to follow @abeba-boop bad instructions anymore.
A staff member of Bloxshade published a fix here: https://github.com/person12306464/Bloxshade/releases/tag/v2.9.0-bloxstrap-fix

**Comment by Elite-Nuke** [comment]
actual goats

**Comment by andrew2341842** [comment]
thats literally a trojan

**Comment by andrew2341842** [comment]
nice he deleted his  comment right after i said it

**Comment by OR555** [comment]
> nice he deleted his comment right after i said it

I deleted it because I got worried it was indeed a Trojan as you said, **although this was shared by a high staff member from the discord server of Bloxshade and I wasn't able to find anything malicious**, but just some **false positives from Microsoft Edge webview installer**. If you would like, **may you please share some details how is it a Trojan** @andrew2341842 ?

**Comment by OR555** [comment]
Here are better instructions how to install Bloxshade with Bloxstrap if anyone wants to use both.

This is the current reason why Bloxshade doesn't work, according to the creator of Bloxshade:
> bloxstrap updated how it handles its file path in version 2.8.0 and i have not had time to update bloxshade yet

This means you can't install Bloxshade with Bloxstrap, but you can install it with the original Roblox.
Bloxshade uses an executable called `eurotrucks2.exe` to enable shaders, you can take a copy of it and place it inside a Bloxstrap executable folder to fix it.

Here's a step by step guide:
1. Uninstall Bloxstrap.
2. Download Roblox.
3. Install Bloxshade.
4. Navigate to Roblox's path folder through it's desktop shortcut, locate and copy `eurotrucks2.exe` to someplace you want to keep it
(keep it as a backup in case Roblox updates and removes it somehow).
5. Install Bloxstrap.
6. **COPY** the **COPIED**  `eurotrucks2.exe` to the Bloxstrap Roblox folder.
7. Create a shortcut of `eurotrucks2.exe` and place it on your desktop.

That's it, now in order to use Bloxshade with Bloxstrap you must run the `eurotrucks2.exe` shortcut.
If you're willing to risk it and use a fix version currently released by one of the high staff of Bloxshade, you can get it by joining the discord server and looking for it here: https://discord.com/invite/QvCrwVf6Mb

**Comment by andrew2341842** [comment]
oh shit mb bro then i think it was just my microsoft thingy too cuz it said it was a trojan
edit: it was my windows defender thingy telling me to not download it

**Comment by OR555** [comment]
> oh shit mb bro then i think it was just my microsoft thingy too cuz it said it was a trojan

It's alright don't worry about it.
You can follow the other guide I sent if you don't want to use that other fix release

**Comment by andrew2341842** [comment]
hey for the roblox folder do i click it once and put next to player or do i click on player too

**Comment by Extravi** [comment]
its been fixed https://github.com/Extravi/Bloxshade/releases/tag/v2.8.16
